/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: BossMission.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @BossMission: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@BossMission()
	{
		this.StartPassage = "Boss Mission";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Boss Mission

	void passage1_Init()
	{
		this.Passages[@"Boss Mission"] = new StoryPassage(@"Boss Mission", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Você encontrou a carta! Era tudo que eu precisava");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Agora posso passar?", "Agora posso passar?", null);
		yield break;
	}


	// .............
	// #2: Agora posso passar?

	void passage2_Init()
	{
		this.Passages[@"Agora posso passar?"] = new StoryPassage(@"Agora posso passar?", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Claro que sim, passe!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Obrigado", "Obrigado", null);
		yield break;
	}


	// .............
	// #3: Obrigado

	void passage3_Init()
	{
		this.Passages[@"Obrigado"] = new StoryPassage(@"Obrigado", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}