/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: HelenaDialogue2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @HelenaDialogue2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@HelenaDialogue2()
	{
		this.StartPassage = "Passagem Sem Nome";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Passagem Sem Nome

	void passage1_Init()
	{
		this.Passages[@"Passagem Sem Nome"] = new StoryPassage(@"Passagem Sem Nome", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Well, June, I think it's time now... You can call yourself a giraffe.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Oh... Thanks!", "Oh... Thanks!", null);
		yield break;
	}


	// .............
	// #2: Oh... Thanks!

	void passage2_Init()
	{
		this.Passages[@"Oh... Thanks!"] = new StoryPassage(@"Oh... Thanks!", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("I have a request for you... Of course, if you're willing to do it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Sure, I'll do it!", "Sure, I'll do it!", null);
		yield break;
	}


	// .............
	// #3: Sure, I'll do it!

	void passage3_Init()
	{
		this.Passages[@"Sure, I'll do it!"] = new StoryPassage(@"Sure, I'll do it!", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("I invite you to join the cause and move forward with us. With your skills, you're more than suited for the task.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("And what do I have to do?", "And what do I have to do?", null);
		yield break;
	}


	// .............
	// #4: And what do I have to do?

	void passage4_Init()
	{
		this.Passages[@"And what do I have to do?"] = new StoryPassage(@"And what do I have to do?", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("We are unable to access a key part of the city because one of the Jackal leaders, Elliot, is killing every single one who approaches and doesn't have a permission granted by the Government. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Oh my god! And how can I help you?", "Oh my god! And how can I help you?", null);
		yield break;
	}


	// .............
	// #5: Oh my god! And how can I help you?

	void passage5_Init()
	{
		this.Passages[@"Oh my god! And how can I help you?"] = new StoryPassage(@"Oh my god! And how can I help you?", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("If you try your new abilities, maybe you can find his sister and talk to her. One of our sources said she may listen and help us, because she hates her brother.");
		yield return lineBreak();
		yield return text("See if you can find a way to learn something that could help us get access to the other part of the city.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Fine, I'll find her", "Fine, I'll find her", null);
		yield break;
	}


	// .............
	// #6: Fine, I'll find her

	void passage6_Init()
	{
		this.Passages[@"Fine, I'll find her"] = new StoryPassage(@"Fine, I'll find her", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Here, have this.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What's this?", "What's this?", null);
		yield break;
	}


	// .............
	// #7: What's this?

	void passage7_Init()
	{
		this.Passages[@"What's this?"] = new StoryPassage(@"What's this?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("It's a staff with powerful essential oils mixed in a way that only us Giraffes know how to do it. It's ancient knowledge and your mother helped us to perfect it. Use it wisely to calm down people who attack you or to go by without hurting others... and yourself.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Right", "Right", null);
		yield break;
	}


	// .............
	// #8: Right

	void passage8_Init()
	{
		this.Passages[@"Right"] = new StoryPassage(@"Right", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("I know you have been through a lot and revisiting your past of violence may be a huge hit on your brain. But trust me, you are ready and you can  do it. I've seen your evolution. Just watch out and try to not be violent with who you encounter, if you can.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Ok, I'll try it", "Ok, I'll try it", null);
		yield break;
	}


	// .............
	// #9: Ok, I'll try it

	void passage9_Init()
	{
		this.Passages[@"Ok, I'll try it"] = new StoryPassage(@"Ok, I'll try it", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}