/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: HelenaDialogue.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @HelenaDialogue: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@HelenaDialogue()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Intro

	void passage1_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Oh, June, my dear, it's an honor to have you here with us. Your mother always talked so much about you. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What do you know about my mother?", "What do you know about my mother?", null);
		yield break;
	}


	// .............
	// #2: What do you know about my mother?

	void passage2_Init()
	{
		this.Passages[@"What do you know about my mother?"] = new StoryPassage(@"What do you know about my mother?", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You probably feel anger when she’s mentioned, don’t you? But let me explain it to you. Unlikely what people had told you, your mother didn’t abandon you. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("WHAT?", "WHAT?", null);
		yield break;
	}


	// .............
	// #3: WHAT?

	void passage3_Init()
	{
		this.Passages[@"WHAT?"] = new StoryPassage(@"WHAT?", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Your mother fought for a better world for you and due to her decision she was forbidden to see you. She wanted you to have the opportunity to experience a world without violence, a more fair world. ");
		yield return lineBreak();
		yield return text("What we live here is her legacy. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Tell me more about that", "Tell me more about that", null);
		yield break;
	}


	// .............
	// #4: Tell me more about that

	void passage4_Init()
	{
		this.Passages[@"Tell me more about that"] = new StoryPassage(@"Tell me more about that", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Patricia was a pioneer when it came to Nonviolent Communication. Why don’t you go to the study room to learn more about this technique for overcoming conflicts? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Ok, I'll give it a try", "Ok, I'll give it a try", null);
		yield break;
	}


	// .............
	// #5: Ok, I'll give it a try

	void passage5_Init()
	{
		this.Passages[@"Ok, I'll give it a try"] = new StoryPassage(@"Ok, I'll give it a try", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("We're glad you're here. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("END", "END", null);
		yield break;
	}


	// .............
	// #6: END

	void passage6_Init()
	{
		this.Passages[@"END"] = new StoryPassage(@"END", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}