/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: PhoneMessage.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @PhoneMessage: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@PhoneMessage()
	{
		this.StartPassage = "Passagem Sem Nome";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Passagem Sem Nome

	void passage1_Init()
	{
		this.Passages[@"Passagem Sem Nome"] = new StoryPassage(@"Passagem Sem Nome", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Ms. June, we recently received the level’s report and we noticed that Floor 49 has greatly reduced the rate of violence.");
		yield return lineBreak();
		yield return text("We need you to go there and find out more about this information.");
		yield return lineBreak();
		yield return text("Security guards are waiting for you. ");
		yield return lineBreak();
		yield return link("Ok", "Ok", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Ok

	void passage2_Init()
	{
		this.Passages[@"Ok"] = new StoryPassage(@"Ok", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Use the WASD keys move around");
		yield return lineBreak();
		yield return text("Hold SHIFT to run");
		yield return lineBreak();
		yield return text("Hold CTRL to crouch");
		yield return lineBreak();
		yield return link("Fine", "Fine", null);
		yield break;
	}


	// .............
	// #3: Fine

	void passage3_Init()
	{
		this.Passages[@"Fine"] = new StoryPassage(@"Fine", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Use the right mouse button to draw the weapon.");
		yield return lineBreak();
		yield return text("Move the mouse to aim.");
		yield return lineBreak();
		yield return text("Click the left mouse button to shoot.");
		yield return lineBreak();
		yield return text("Press F to kill while undetectable");
		yield return lineBreak();
		yield return link("Ok.", "Ok.", null);
		yield break;
	}


	// .............
	// #4: Ok.

	void passage4_Init()
	{
		this.Passages[@"Ok."] = new StoryPassage(@"Ok.", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}