/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Quadro3.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Quadro3: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Quadro3()
	{
		this.StartPassage = "Passagem Sem Nome";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Passagem Sem Nome

	void passage1_Init()
	{
		this.Passages[@"Passagem Sem Nome"] = new StoryPassage(@"Passagem Sem Nome", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Choice, responsibility, peace:");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("1 - Taking responsibility for our feelings ");
		yield return lineBreak();
		yield return text("2 - Taking responsibility for our actions ");
		yield return lineBreak();
		yield return text("3 - Living in peace with unmet needs ");
		yield return lineBreak();
		yield return text("4 - Increasing capacity for meeting needs");
		yield return lineBreak();
		yield return text("5 - Increasing capacity for meeting the present moment ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("END", "END", null);
		yield break;
	}


	// .............
	// #2: END

	void passage2_Init()
	{
		this.Passages[@"END"] = new StoryPassage(@"END", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}