/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: ThimotheeDialogue.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @ThimotheeDialogue: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@ThimotheeDialogue()
	{
		this.StartPassage = "Passagem Sem Nome";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Passagem Sem Nome

	void passage1_Init()
	{
		this.Passages[@"Passagem Sem Nome"] = new StoryPassage(@"Passagem Sem Nome", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("We can't get out of darkness. You're the one to blame");
		yield return lineBreak();
		yield return link("<NEXT>", "<NEXT>", null);
		yield break;
	}


	// .............
	// #2: <NEXT>

	void passage2_Init()
	{
		this.Passages[@"<NEXT>"] = new StoryPassage(@"<NEXT>", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Clique duas vezes nessa passagem para editá-la.");
		yield break;
	}


}